#!/usr/bin/env bash

# This script is responsible for preparing a release commit
# There are few places (e.g. Terraform module) that rely on the release tag to be up-to-date in proper releases
set -euo pipefail

if [[ -z "${1:-}" ]]; then
    echo "prepare_release <tag_name>"
    exit 1
fi

tag_name="$1"

root_dir="$(dirname "$0")/.."
cd "$root_dir" || exit 1

# First some sanity checks
if ! [[ "${tag_name}" =~ v.*.*.* ]]; then
    echo "Provided tag name does not match the v.*.*.* format, aborting"
    exit 1
fi

branch_name="$(git rev-parse --abbrev-ref HEAD)"
if [[ "${branch_name}" != "master" ]]; then
    echo "Checked out branch is not the main branch, aborting"
    exit 1
fi

if [[ "$(git rev-parse HEAD)" != "$(git rev-parse "origin/${branch_name}")" ]] && [[ "${SKIP_UPSTREAM_CHECK:-}" != "true" ]]; then
    echo "Checked out branch is not in sync with origin, aborting"
    echo "You can set SKIP_UPSTREAM_CHECK=true to disable this check"
    exit 1
fi

if [[ -n "$(git status --porcelain --untracked-files=no)" ]]; then
    echo "Checked out branch has uncommited changes, aborting"
    exit 1
fi

if [[ -n "$(git tag -l "${tag_name}")" ]]; then
    echo "Tag ${tag_name} already exists, aborting"
    exit 1
fi

# Now perform the necessary changes
#sed -i "s/default     = \".*\" #SED_RELEASE_VERSION/default     = \"$tag_name\" #SED_RELEASE_VERSION/" terraform/variables.tf
#git add terraform/variables.tf

sed -i "s/@.* #SED_RELEASE_VERSION/@$tag_name #SED_RELEASE_VERSION/" README.md
sed -i "s/:.* #SED_RELEASE_VERSION/:$tag_name #SED_RELEASE_VERSION/" README.md
git add README.md

# And create a commit and a tag
git commit -m "chore: prepare release of ${tag_name}"
git tag "${tag_name}"

# TODO: is it a wise idea to just make it part of the script?
echo "Release has been prepared, you can now push it upstream with the following commands"
echo "git push origin ${branch_name} && git push origin ${tag_name}"
