name: Build Images

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
      - "develop"
    tags:
      - "v*"
  pull_request:
    branches:
      - "master"

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ${{ github.repository }}

jobs:
  docker:
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - component: "s3_monitor"
          - component: "eml_unpack_attachments"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # Allow image pushes
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}_${{ matrix.cfg.component }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.cfg.component }}
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
