---
name: Run tests

on:
  push:
  workflow_dispatch:
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      go_version: "1.23"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go_version }}

      - run: |
          go test -v ./...
